include ./common.inc

##########################################################################################
## crypting tools:
crypting-init:
	$(MAKE) 

home: ## prints home dir
	echo $(HOME)
lorem: ## ipsum dolor sit
	echo "this is lorem target"
reset.yourmum: ### it is what it is
	echo "how about that"

##########################################################################################
## deploying:

ipsum: #### lorem sit
	echo "whats up?"
convert.it: ##### i am feeling lucky
	echo "back to basics"
delete.it: prompt_me ### test the prompt_me target
	echo "now delete something"
