# Name of the include file
TARGET_FILE = ./makefiles_inc/makefile_essential_lib.inc
DOWNLOAD_URL = https://raw.githubusercontent.com/OliPelz/makefile-libs/2bba343984b1fcbe95ddab814cd5ee6d4f947c84/makefile_essential_lib.inc

include ../makefile_essential_lib.inc
##########################################################################################
## building:

home: ## prints home dir
	echo $(HOME)
lorem: ## ipsum dolor sit
	echo "this is lorem target"
reset.yourmum: ### it is what it is
	echo "how about that"

##########################################################################################
## deploying:

ipsum: #### lorem sit
	echo "whats up?"
convert.it: ##### i am feeling lucky
	echo "back to basics"
delete.it: prompt_me ### test the prompt_me target
	echo "now delete something"
